src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password     
     * @Assert\NotBlank(groups={"registration"})
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $lastLogin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="belongsTo")
     */
    private $assignedOrders;
    
    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    public function __construct()
    {
        $this->assignedOrders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
    
    
    /**
     * @see UserInterface
     */
    public function getDisplayRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER       
        
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    
    public function getAvatarUrl(string $size = '24'): string
    {
        $url = 'https://ui-avatars.com/api/?name='.mb_substr($this->getUsername(),-2);
        
        if ($size)
            $url .= sprintf('&size=%d', $size);
            return $url;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getAssignedOrders(): Collection
    {
        return $this->assignedOrders;
    }

    public function addAssignedOrder(Order $assignedOrder): self
    {
        if (!$this->assignedOrders->contains($assignedOrder)) {
            $this->assignedOrders[] = $assignedOrder;
            $assignedOrder->setBelongsTo($this);
        }

        return $this;
    }

    public function removeAssignedOrder(Order $assignedOrder): self
    {
        if ($this->assignedOrders->contains($assignedOrder)) {
            $this->assignedOrders->removeElement($assignedOrder);
            // set the owning side to null (unless already changed)
            if ($assignedOrder->getBelongsTo() === $this) {
                $assignedOrder->setBelongsTo(null);
            }
        }

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }
}

src/Form/My/UserType.php
<?php

namespace App\Form\My;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Contracts\Translation\TranslatorInterface;
class UserType extends AbstractType
{
    
    /**
     * @var TranslatorInterface
     */
    private $translator;
    
    public function __construct(TranslatorInterface  $translator)
    {
        $this->translator = $translator;        
    }
    
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username',null,[
                'label'=>'用户名'
            ])
            ->add('passwordOld',PasswordType::class,[
                'mapped'=>false,
                'label'=>'原密码',
                'required'=>false,
            ])
           ->add('passwordNew',PasswordType::class,[
                'mapped'=>false,
                'label'=>'新密码',
                'required'=>false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            
        ]);
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Contracts\Translation\TranslatorInterface;
class UserType extends AbstractType
{
    
    /**
     * @var TranslatorInterface
     */
    private $translator;
    
    public function __construct(TranslatorInterface  $translator)
    {
        $this->translator = $translator;        
    }
    
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username',null,[
                'label'=>'用户名'
            ])
            ->add('roles',ChoiceType::class,[
                'choices'  =>[
                 //   $this->translator->trans('ROLE_SUPER_ADMIN') => 'ROLE_SUPER_ADMIN',
                    $this->translator->trans('ROLE_ADMIN') => 'ROLE_ADMIN',
                    $this->translator->trans('ROLE_CUSTOMER') => 'ROLE_CUSTOMER',                 
                ],                
                'label'=>'角色',
                'multiple'=>true,
                'required'=>false,
            ])
           ->add('password',PasswordType::class,[
                'mapped'=>false,
                'label'=>'密码',
                'required'=>false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Form\My\UserType as MyUserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface; 
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Form\FormError;
use Symfony\Contracts\Translation\TranslatorInterface;
/**
 * @Route("/user") 
 */
class UserController extends AbstractController
{
    /**
     * @var TranslatorInterface
     */
    private $translator;
    
    private  $passwordEncoder;
    
    public function __construct(TranslatorInterface  $translator,UserPasswordEncoderInterface $passwordEncoder)
    {     
        $this->passwordEncoder = $passwordEncoder;    
        $this->translator = $translator;    
        
    }
    
    /**
     * @Route("/", name="user_index", methods={"GET"})
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user,[
         //   'validation_groups' => ['registration']
        ]);
        $form->handleRequest($request);
  
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();       
            $user->setPassword($this->passwordEncoder->encodePassword($user,$form->get('password')->getData()));        
            $entityManager->persist($user);
            $entityManager->flush();
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    
    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($password=$form->get('password')->getData()){                
                $user->setPassword($this->passwordEncoder->encodePassword($user,$password));
            }
            
            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    
    
    
    
    /**
     * @Route("/changePassword", name="user_changePassword", methods={"GET","POST"})
     * @IsGranted({"ROLE_USER"})
     */
    public function user_changePassword(Request $request): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(MyUserType::class, $user);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $passwordOld = $form->get('passwordOld')->getData();
           
            
            if($this->passwordEncoder->isPasswordValid($user, $passwordOld)){
            
                if( $passwordNew = $form->get('passwordNew')->getData()){
                    $user->setPassword($this->passwordEncoder->encodePassword($user,$passwordNew));
                }
                
                $this->getDoctrine()->getManager()->flush();
                
                $this->addFlash('warning', $this->translator->trans('Your password has been updated'));
                return $this->redirectToRoute('user_changePassword');
            }
            else {
                $form->addError(new FormError($this->translator->trans('You password is not correct')));
                return $this->render('user/my/edit.html.twig', [
                    'form' => $form->createView(),
                ]);
            }
            
        }
        
        return $this->render('user/my/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    
    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        
        
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }
    
    
    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }
        
        return $this->redirectToRoute('user_index');
    }
 
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}编辑用户:{{ user.username }}{% endblock %}
{%  block content_header %}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <h4>编辑用户:{{ user.username }}</h4>
          </div>
        </div>
 </div>
{% endblock  %}

{% block body %}

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{%  block content_header %}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <h4>用户列表</h4>
          </div>
        </div>
 </div>
{% endblock  %}


{% block body %}    

    <table class="table">
        <thead>
            <tr>
                <th>编号</th>
                <th>用户名</th>
                <th>角色</th>               
                <th class="d-none d-sm-table-cell">最近登录时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>
                    {% for role in user.displayRoles %}                    
                     {{ role|trans }}<br/>                        
                    {% endfor %}      
                </td>                    
                
                
                
                <td class="d-none d-sm-table-cell">{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>                
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}创建用户{% endblock %}
{%  block content_header %}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <h4>创建用户</h4>
          </div>
        </div>
 </div>
{% endblock  %}

{% block body %}    

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}查看用户:{{ user.username }}{% endblock %}


{%  block content_header %}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <h4>查看用户:{{ user.username }}</h4>
          </div>
        </div>
 </div>
{% endblock  %}


{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th>编号</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>用户名</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>角色</th>
                <td> {% for role in user.displayRoles %}                    
                     {{ role|trans }}<br/>                        
                    {% endfor %}
                </td>
            </tr>           
            <tr>
                <th>最近登录</th>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>创建时间</th>
                <td>{{ user.created ? user.created|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}